import anime from "./methods/jikan/anime";
import manga from "./methods/jikan/manga";
import person from "./methods/jikan/person";
import character from "./methods/jikan/character";
import search from "./methods/jikan/search";
import season from "./methods/jikan/season";
import seasonArchive from "./methods/jikan/seasonArchive";
import seasonLater from "./methods/jikan/seasonLater";
import schedule from "./methods/jikan/schedule";
import top from "./methods/jikan/top";
import genre from "./methods/jikan/genre";
import producer from "./methods/jikan/producer";
import magazine from "./methods/jikan/magazine";
import user from "./methods/jikan/user";
import club from "./methods/jikan/club";
import AnimeGenre from "./methods/jikan/types/animeGenre";
import MangaGenre from "./methods/jikan/types/mangaGenre";
import AnimeType from "./methods/jikan/types/animeType";
import MangaType from "./methods/jikan/types/mangaType";
import AnimeStatus from "./methods/jikan/types/animeStatus";
import MangaStatus from "./methods/jikan/types/mangaStatus";
import AnimeOrderBy from "./methods/jikan/types/animeOrderBy";
import MangaOrderBy from "./methods/jikan/types/mangaOrderBy";
import Sort from "./methods/jikan/types/sort";
import Rating from "./methods/jikan/types/rating";
declare class JikanClient {
    anime: typeof anime;
    manga: typeof manga;
    person: typeof person;
    character: typeof character;
    search: typeof search;
    season: typeof season;
    seasonArchive: typeof seasonArchive;
    seasonLater: typeof seasonLater;
    schedule: typeof schedule;
    top: typeof top;
    genre: typeof genre;
    producer: typeof producer;
    magazine: typeof magazine;
    user: typeof user;
    club: typeof club;
    types: {
        AnimeGenre: typeof AnimeGenre;
        MangaGenre: typeof MangaGenre;
        AnimeType: typeof AnimeType;
        MangaType: typeof MangaType;
        AnimeStatus: typeof AnimeStatus;
        MangaStatus: typeof MangaStatus;
        AnimeOrderBy: typeof AnimeOrderBy;
        MangaOrderBy: typeof MangaOrderBy;
        Sort: typeof Sort;
        Rating: typeof Rating;
    };
}
import login from "./methods/poly/noApiLogin";
import notifications from "./methods/poly/loginRequired/notifications";
import animeEdit from "./methods/poly/loginRequired/animeEdit";
declare class ScraperClient {
    login: typeof login;
    notifications: typeof notifications;
    animeEdit: typeof animeEdit;
}
declare const Mal: JikanClient;
declare const version: any;
export { Mal, version, JikanClient, ScraperClient };
export default Mal;
