import anime from "./methods/jikan_v2/anime";
import manga from "./methods/jikan_v2/manga";
import person from "./methods/jikan_v2/person";
import character from "./methods/jikan_v2/character";
import search from "./methods/jikan_v2/search";
import season from "./methods/jikan_v2/season";
import seasonArchive from "./methods/jikan_v2/seasonArchive";
import seasonLater from "./methods/jikan_v2/seasonLater";
import schedule from "./methods/jikan_v2/schedule";
import top from "./methods/jikan_v2/top";
import genre from "./methods/jikan_v2/genre";
import producer from "./methods/jikan_v2/producer";
import magazine from "./methods/jikan_v2/magazine";
import user from "./methods/jikan_v2/user";
import club from "./methods/jikan_v2/club";
import AnimeGenre from "./methods/jikan_v2/types/animeGenre";
import MangaGenre from "./methods/jikan_v2/types/mangaGenre";
import AnimeType from "./methods/jikan_v2/types/animeType";
import MangaType from "./methods/jikan_v2/types/mangaType";
import AnimeStatus from "./methods/jikan_v2/types/animeStatus";
import MangaStatus from "./methods/jikan_v2/types/mangaStatus";
import AnimeOrderBy from "./methods/jikan_v2/types/animeOrderBy";
import MangaOrderBy from "./methods/jikan_v2/types/mangaOrderBy";
import Sort from "./methods/jikan_v2/types/sort";
import Rating from "./methods/jikan_v2/types/rating";
declare class JikanClient {
    anime: typeof anime;
    manga: typeof manga;
    person: typeof person;
    character: typeof character;
    search: typeof search;
    season: typeof season;
    seasonArchive: typeof seasonArchive;
    seasonLater: typeof seasonLater;
    schedule: typeof schedule;
    top: typeof top;
    genre: typeof genre;
    producer: typeof producer;
    magazine: typeof magazine;
    user: typeof user;
    club: typeof club;
    types: {
        AnimeGenre: typeof AnimeGenre;
        MangaGenre: typeof MangaGenre;
        AnimeType: typeof AnimeType;
        MangaType: typeof MangaType;
        AnimeStatus: typeof AnimeStatus;
        MangaStatus: typeof MangaStatus;
        AnimeOrderBy: typeof AnimeOrderBy;
        MangaOrderBy: typeof MangaOrderBy;
        Sort: typeof Sort;
        Rating: typeof Rating;
    };
}
declare const Mal: JikanClient;
declare const version: any;
export { Mal, version, JikanClient };
export default Mal;
