import anime from "./methods/jikan/anime";
import manga from "./methods/jikan/manga";
import person from "./methods/jikan/person";
import character from "./methods/jikan/character";
import season from "./methods/jikan/season";
import seasonArchive from "./methods/jikan/seasonArchive";
import schedule from "./methods/jikan/schedule";
import search from "./methods/jikan/search";
import top from "./methods/jikan/top";
import genre from "./methods/jikan/genre";
import producer from "./methods/jikan/producer";
import user from "./methods/jikan/user";
import avatar from "./methods/poly/avatar";
import list from "./methods/poly/list";
import animeUpdates from "./methods/poly/animeUpdates";
import days from "./methods/poly/days";
import login from "./methods/poly/noApiLogin";
import notifications from "./methods/poly/loginRequired/notifications";
import animeEdit from "./methods/poly/loginRequired/animeEdit";
import MalMobileClient from "./methods/poly/mobileApi/malMobileClient";
declare class MalClient {
    anime: typeof anime;
    manga: typeof manga;
    person: typeof person;
    character: typeof character;
    search: typeof search;
    season: typeof season;
    seasonArchive: typeof seasonArchive;
    schedule: typeof schedule;
    top: typeof top;
    genre: typeof genre;
    producer: typeof producer;
    user: typeof user;
    avatar: typeof avatar;
    list: typeof list;
    animeUpdates: typeof animeUpdates;
    days: typeof days;
    login: typeof login;
    notifications: typeof notifications;
    animeEdit: typeof animeEdit;
}
declare const Mal: MalClient;
declare const version: any;
export { Mal, version, MalClient, MalMobileClient };
export default Mal;
