import anime from "./methods/jikan/anime.js";
import manga from "./methods/jikan/manga.js";
import person from "./methods/jikan/person.js";
import character from "./methods/jikan/character.js";
import search from "./methods/jikan/search.js";
import season from "./methods/jikan/season.js";
import seasonArchive from "./methods/jikan/seasonArchive.js";
import seasonLater from "./methods/jikan/seasonLater.js";
import schedule from "./methods/jikan/schedule.js";
import top from "./methods/jikan/top.js";
import genre from "./methods/jikan/genre.js";
import producer from "./methods/jikan/producer.js";
import magazine from "./methods/jikan/magazine.js";
import user from "./methods/jikan/user.js";
import club from "./methods/jikan/club.js";
import AnimeGenre from "./methods/jikan/types/animeGenre.js";
import MangaGenre from "./methods/jikan/types/mangaGenre.js";
import AnimeType from "./methods/jikan/types/animeType.js";
import MangaType from "./methods/jikan/types/mangaType.js";
import AnimeStatus from "./methods/jikan/types/animeStatus.js";
import MangaStatus from "./methods/jikan/types/mangaStatus.js";
import AnimeOrderBy from "./methods/jikan/types/animeOrderBy.js";
import MangaOrderBy from "./methods/jikan/types/mangaOrderBy.js";
import Sort from "./methods/jikan/types/sort.js";
import Rating from "./methods/jikan/types/rating.js";
declare class JikanClient {
    anime: typeof anime;
    manga: typeof manga;
    person: typeof person;
    character: typeof character;
    search: typeof search;
    season: typeof season;
    seasonArchive: typeof seasonArchive;
    seasonLater: typeof seasonLater;
    schedule: typeof schedule;
    top: typeof top;
    genre: typeof genre;
    producer: typeof producer;
    magazine: typeof magazine;
    user: typeof user;
    club: typeof club;
    types: {
        AnimeGenre: typeof AnimeGenre;
        MangaGenre: typeof MangaGenre;
        AnimeType: typeof AnimeType;
        MangaType: typeof MangaType;
        AnimeStatus: typeof AnimeStatus;
        MangaStatus: typeof MangaStatus;
        AnimeOrderBy: typeof AnimeOrderBy;
        MangaOrderBy: typeof MangaOrderBy;
        Sort: typeof Sort;
        Rating: typeof Rating;
    };
}
declare const Mal: JikanClient;
export { Mal, JikanClient, };
export default Mal;
