import AnimeInfo from "./info";
import Episodes from "./episodes";
import AnimeCharactersStaff from "./charactersStaff";
import News from "../news/news";
import Pictures from "./pictures";
import AnimeVideos from "./videos";
import AnimeStats from "./stats";
import Forum from "./forum";
import MoreInfo from "./moreInfo";
import AnimeReviews from "./reviews";
import Recommendations from "./recommendations";
export { AnimeInfo, AnimeCharactersStaff, Episodes, News, Pictures, AnimeVideos, AnimeStats, Forum, MoreInfo, AnimeReviews, Recommendations, };
