var AnimeGenre;
(function (AnimeGenre) {
    AnimeGenre[AnimeGenre["action"] = 1] = "action";
    AnimeGenre[AnimeGenre["adventure"] = 2] = "adventure";
    AnimeGenre[AnimeGenre["cars"] = 3] = "cars";
    AnimeGenre[AnimeGenre["comedy"] = 4] = "comedy";
    AnimeGenre[AnimeGenre["dementia"] = 5] = "dementia";
    AnimeGenre[AnimeGenre["demons"] = 6] = "demons";
    AnimeGenre[AnimeGenre["mystery"] = 7] = "mystery";
    AnimeGenre[AnimeGenre["drama"] = 8] = "drama";
    AnimeGenre[AnimeGenre["ecchi"] = 9] = "ecchi";
    AnimeGenre[AnimeGenre["fantasy"] = 10] = "fantasy";
    AnimeGenre[AnimeGenre["game"] = 11] = "game";
    AnimeGenre[AnimeGenre["hentai"] = 12] = "hentai";
    AnimeGenre[AnimeGenre["historical"] = 13] = "historical";
    AnimeGenre[AnimeGenre["horror"] = 14] = "horror";
    AnimeGenre[AnimeGenre["kids"] = 15] = "kids";
    AnimeGenre[AnimeGenre["magic"] = 16] = "magic";
    AnimeGenre[AnimeGenre["martialArts"] = 17] = "martialArts";
    AnimeGenre[AnimeGenre["mecha"] = 18] = "mecha";
    AnimeGenre[AnimeGenre["music"] = 19] = "music";
    AnimeGenre[AnimeGenre["parody"] = 20] = "parody";
    AnimeGenre[AnimeGenre["samurai"] = 21] = "samurai";
    AnimeGenre[AnimeGenre["romance"] = 22] = "romance";
    AnimeGenre[AnimeGenre["school"] = 23] = "school";
    AnimeGenre[AnimeGenre["sciFi"] = 24] = "sciFi";
    AnimeGenre[AnimeGenre["shoujo"] = 25] = "shoujo";
    AnimeGenre[AnimeGenre["shoujoAi"] = 26] = "shoujoAi";
    AnimeGenre[AnimeGenre["shounen"] = 27] = "shounen";
    AnimeGenre[AnimeGenre["shounenAi"] = 28] = "shounenAi";
    AnimeGenre[AnimeGenre["space"] = 29] = "space";
    AnimeGenre[AnimeGenre["sports"] = 30] = "sports";
    AnimeGenre[AnimeGenre["superPower"] = 31] = "superPower";
    AnimeGenre[AnimeGenre["vampire"] = 32] = "vampire";
    AnimeGenre[AnimeGenre["yaoi"] = 33] = "yaoi";
    AnimeGenre[AnimeGenre["yuri"] = 34] = "yuri";
    AnimeGenre[AnimeGenre["harem"] = 35] = "harem";
    AnimeGenre[AnimeGenre["sliceOfLife"] = 36] = "sliceOfLife";
    AnimeGenre[AnimeGenre["supernatural"] = 37] = "supernatural";
    AnimeGenre[AnimeGenre["military"] = 38] = "military";
    AnimeGenre[AnimeGenre["police"] = 39] = "police";
    AnimeGenre[AnimeGenre["psychological"] = 40] = "psychological";
    AnimeGenre[AnimeGenre["thriller"] = 41] = "thriller";
    AnimeGenre[AnimeGenre["seinen"] = 42] = "seinen";
    AnimeGenre[AnimeGenre["josei"] = 43] = "josei";
})(AnimeGenre || (AnimeGenre = {}));
export default AnimeGenre;
//# sourceMappingURL=animeGenre.js.map