import anime from "./jikan/anime.js";
import manga from "./jikan/manga.js";
import person from "./jikan/person.js";
import character from "./jikan/character.js";
import search from "./jikan/search.js";
import season from "./jikan/season.js";
import seasonArchive from "./jikan/seasonArchive.js";
import seasonLater from "./jikan/seasonLater.js";
import schedule from "./jikan/schedule.js";
import top from "./jikan/top.js";
import genre from "./jikan/genre.js";
import producer from "./jikan/producer.js";
import magazine from "./jikan/magazine.js";
import user from "./jikan/user.js";
import club from "./jikan/club.js";
import AnimeGenre from "./jikan/types/animeGenre.js";
import MangaGenre from "./jikan/types/mangaGenre.js";
import AnimeType from "./jikan/types/animeType.js";
import MangaType from "./jikan/types/mangaType.js";
import AnimeStatus from "./jikan/types/animeStatus.js";
import MangaStatus from "./jikan/types/mangaStatus.js";
import AnimeOrderBy from "./jikan/types/animeOrderBy.js";
import MangaOrderBy from "./jikan/types/mangaOrderBy.js";
import Sort from "./jikan/types/sort.js";
import Rating from "./jikan/types/rating.js";
declare class JikanClient {
    anime: typeof anime;
    manga: typeof manga;
    person: typeof person;
    character: typeof character;
    search: typeof search;
    season: typeof season;
    seasonArchive: typeof seasonArchive;
    seasonLater: typeof seasonLater;
    schedule: typeof schedule;
    top: typeof top;
    genre: typeof genre;
    producer: typeof producer;
    magazine: typeof magazine;
    user: typeof user;
    club: typeof club;
    types: {
        AnimeGenre: typeof AnimeGenre;
        MangaGenre: typeof MangaGenre;
        AnimeType: typeof AnimeType;
        MangaType: typeof MangaType;
        AnimeStatus: typeof AnimeStatus;
        MangaStatus: typeof MangaStatus;
        AnimeOrderBy: typeof AnimeOrderBy;
        MangaOrderBy: typeof MangaOrderBy;
        Sort: typeof Sort;
        Rating: typeof Rating;
    };
}
declare const Mal: JikanClient;
export { Mal, JikanClient, };
export default Mal;
