export const search = {
  data: [
    {
      node: {
        id: 30051,
        title: "Sakurasou no Pet na Kanojo",
        main_picture: {
          medium: "https://api-cdn.myanimelist.net/images/manga/2/159577.jpg",
          large: "https://api-cdn.myanimelist.net/images/manga/2/159577l.jpg",
        },
        alternative_titles: {
          synonyms: ["Sakura-sou no Pet na Kanojo"],
          en: "",
          ja: "さくら荘のペットな彼女",
        },
        start_date: "2010-01-10",
        end_date: "2014-03-08",
        synopsis:
          'Kanda Sorata is a second year high school art student who was recently kicked out of the school\'s dorm because he was found keeping a cat in his room. Sorata begins to live in the apartment house "Sakurasou", infamous for its eccentric residents. Here, Sorata is asked to take care of one of his classmates, Shiina Mashiro. Although she is a brilliant, world-class painter, she is extremely clumsy and lacking in common sense.  And thus begins the story of the master and his pet.',
        mean: 8.13,
        rank: 476,
        popularity: 1123,
        num_list_users: 9838,
        num_scoring_users: 2110,
        nsfw: "white",
        genres: [
          { id: 22, name: "Romance" },
          { id: 4, name: "Comedy" },
          { id: 36, name: "Slice of Life" },
        ],
        created_at: "1970-01-01T00:00:00+00:00",
        updated_at: "2020-07-15T17:52:58+00:00",
        media_type: "novel",
        status: "finished",
        my_list_status: {
          status: "on_hold",
          is_rereading: false,
          num_volumes_read: 1,
          num_chapters_read: 0,
          score: 8,
          updated_at: "2017-05-02T16:30:48+00:00",
          finish_date: "2017-03-06",
          priority: 0,
          num_times_reread: 0,
          reread_value: 0,
          tags: [],
          comments: "",
        },
        num_volumes: 13,
        num_chapters: 0,
        authors: [
          {
            node: { id: 14013, first_name: "Hajime", last_name: "Kamoshida" },
            role: "Story",
          },
          {
            node: { id: 19950, first_name: "Keiji", last_name: "Mizoguchi" },
            role: "Art",
          },
        ],
      },
    },
    {
      node: {
        id: 88336,
        title: "Sakura",
        main_picture: {
          medium: "https://api-cdn.myanimelist.net/images/manga/1/155104.jpg",
          large: "https://api-cdn.myanimelist.net/images/manga/1/155104l.jpg",
        },
        alternative_titles: {
          synonyms: [
            "Girls Relations Anthology",
            "Goodbye Kastor",
            "Sakura Trick",
          ],
          en: "",
          ja: "SAKURA",
        },
        start_date: "2014-01-27",
        synopsis: "Anthology by various mangaka.",
        mean: 7.47,
        rank: 34695,
        popularity: 14221,
        num_list_users: 529,
        num_scoring_users: 70,
        nsfw: "white",
        genres: [
          { id: 37, name: "Supernatural" },
          { id: 4, name: "Comedy" },
          { id: 23, name: "School" },
          { id: 8, name: "Drama" },
          { id: 26, name: "Shoujo Ai" },
        ],
        created_at: "1970-01-01T00:00:00+00:00",
        updated_at: "2020-05-28T14:01:02+00:00",
        media_type: "manga",
        status: "currently_publishing",
        num_volumes: 0,
        num_chapters: 0,
        authors: [
          {
            node: { id: 7605, first_name: "Auri", last_name: "Hirao" },
            role: "Story & Art",
          },
          {
            node: { id: 9207, first_name: "Ikki", last_name: "Sanada" },
            role: "Story & Art",
          },
          {
            node: { id: 11113, first_name: "Moto", last_name: "Momono" },
            role: "Story & Art",
          },
          {
            node: { id: 22681, first_name: "", last_name: "Tachi" },
            role: "Story & Art",
          },
          {
            node: { id: 24351, first_name: "Nanagou", last_name: "Hoshikuzu" },
            role: "Story & Art",
          },
          {
            node: { id: 26657, first_name: "Akame", last_name: "Kiyose" },
            role: "Story & Art",
          },
          {
            node: { id: 29429, first_name: "Aya", last_name: "Fumio" },
            role: "Story & Art",
          },
          {
            node: { id: 37856, first_name: "", last_name: "YUI_7" },
            role: "Story & Art",
          },
        ],
      },
    },
    {
      node: {
        id: 2061,
        title: "Sakuran",
        main_picture: {
          medium: "https://api-cdn.myanimelist.net/images/manga/1/158793.jpg",
          large: "https://api-cdn.myanimelist.net/images/manga/1/158793l.jpg",
        },
        alternative_titles: { synonyms: [], en: "Sakuran", ja: "さくらん" },
        start_date: "2001-08-20",
        end_date: "2003-05-27",
        synopsis:
          'The story follows Kiyoha, sold into a brothel as a child and forced to work as a maid and her rise to prominence as one of the top-ranking courtesans in Yoshiwara. The allure of the "flower and willow world" as it was called by artists in the day is underscored by the very real tragedy, heartbreak and difficult lives led by those seemingly glamorous courtesans. Will Kiyoha\'s fox-like wiles give her a chance to break free of her gilded cage? Or will her fighting spirit ruin her chances of ever escaping the brothel?\n\n(Source: Vertical)',
        mean: 7.13,
        rank: 6133,
        popularity: 4129,
        num_list_users: 2810,
        num_scoring_users: 1165,
        nsfw: "white",
        genres: [
          { id: 8, name: "Drama" },
          { id: 13, name: "Historical" },
          { id: 41, name: "Seinen" },
        ],
        created_at: "1970-01-01T00:00:00+00:00",
        updated_at: "2020-06-02T19:06:59+00:00",
        media_type: "manga",
        status: "finished",
        num_volumes: 1,
        num_chapters: 13,
        authors: [
          {
            node: { id: 2340, first_name: "Moyoco", last_name: "Anno" },
            role: "Story & Art",
          },
        ],
      },
    },
    {
      node: {
        id: 98961,
        title: "NPC to Kurasou!",
        main_picture: {
          medium: "https://api-cdn.myanimelist.net/images/manga/3/194247.jpg",
          large: "https://api-cdn.myanimelist.net/images/manga/3/194247l.jpg",
        },
        alternative_titles: {
          synonyms: [],
          en: "Let's Live With Non Player Character!",
          ja: "NPCと暮らそう！",
        },
        start_date: "2016-06-11",
        synopsis: "",
        mean: 7.63,
        rank: 19219,
        popularity: 29393,
        num_list_users: 96,
        num_scoring_users: 9,
        nsfw: "white",
        genres: [
          { id: 9, name: "Ecchi" },
          { id: 10, name: "Fantasy" },
          { id: 11, name: "Game" },
          { id: 22, name: "Romance" },
          { id: 35, name: "Harem" },
          { id: 24, name: "Sci-Fi" },
        ],
        created_at: "1970-01-01T00:00:00+00:00",
        updated_at: "2017-04-06T22:03:12+00:00",
        media_type: "novel",
        status: "currently_publishing",
        num_volumes: 0,
        num_chapters: 0,
        authors: [
          {
            node: { id: 39754, first_name: "", last_name: "Gustav" },
            role: "Art",
          },
          {
            node: { id: 41413, first_name: "", last_name: "Damin" },
            role: "Story",
          },
        ],
      },
    },
    {
      node: {
        id: 56955,
        title: "Sakurasaku Syndrome",
        main_picture: {
          medium: "https://api-cdn.myanimelist.net/images/manga/3/98955.jpg",
          large: "https://api-cdn.myanimelist.net/images/manga/3/98955l.jpg",
        },
        alternative_titles: {
          synonyms: ["Sakurasaku Shoukougun"],
          en: "",
          ja: "サクラサク症候群〈シンドローム〉",
        },
        start_date: "2013-02-04",
        end_date: "2014-09-04",
        synopsis:
          "Childhood friends Wakatake and Kagetora meet again after not seeing each other for more than 10 years.\n\nWakatake is a boy who takes his studies extremely serious, as he is to take over the medical clinic of his parents one day. Kagetora is an impulsive girl, who spends most of her time fighting outside on the streets, instead of the class room. Now that Kagetora decided to enter one of the most prestigious high schools of the country to pursue the love of her life, she needs Wakatake to help her to pass the entrance test...\n\n(Source: MU) ",
        mean: 7.27,
        rank: 4545,
        popularity: 1830,
        num_list_users: 6273,
        num_scoring_users: 3003,
        nsfw: "white",
        genres: [
          { id: 22, name: "Romance" },
          { id: 23, name: "School" },
          { id: 36, name: "Slice of Life" },
          { id: 8, name: "Drama" },
          { id: 27, name: "Shounen" },
        ],
        created_at: "1970-01-01T00:00:00+00:00",
        updated_at: "2020-07-15T20:13:49+00:00",
        media_type: "manga",
        status: "finished",
        num_volumes: 4,
        num_chapters: 19,
        authors: [
          {
            node: { id: 24721, first_name: "Renji", last_name: "Hoshi" },
            role: "Story & Art",
          },
        ],
      },
    },
    {
      node: {
        id: 511,
        title: "Sakura Taisen",
        main_picture: {
          medium: "https://api-cdn.myanimelist.net/images/manga/2/176.jpg",
          large: "https://api-cdn.myanimelist.net/images/manga/2/176l.jpg",
        },
        alternative_titles: {
          synonyms: ["Sakura Wars"],
          en: "Sakura Wars",
          ja: "サクラ大戦",
        },
        start_date: "2002-06-26",
        end_date: "2008-12-26",
        synopsis:
          "The year is 1921, and this is a Tokyo where monstrous steam-powered robots crash a flower-viewing party only to be cut down samurai-style by a young girl in a kimono and traditional hakama pants.\n\nIt's eight years after the horrific Demon War, and Japan is a peaceful prosperous place. Meet Ensign Ogami Ichiro, who has just graduated from the Naval Academy. He's assigned to a base in Tokyo, but soon discovers that his headquarters is the Imperial Theater and his first mission is collecting tickets at the gate. He gamely goes about his menial jobs at the theater, surrounded by beautiful girls who seem to know a lot more about what's going on than he does, but he's about to be swept into a roiling world of robots, demons, and hot girls in uniform.\n\n(Source: Tokyopop)",
        mean: 6.9,
        rank: 8614,
        popularity: 6692,
        num_list_users: 1608,
        num_scoring_users: 606,
        nsfw: "white",
        genres: [
          { id: 1, name: "Action" },
          { id: 22, name: "Romance" },
          { id: 37, name: "Supernatural" },
        ],
        created_at: "1970-01-01T00:00:00+00:00",
        updated_at: "2020-07-12T23:37:49+00:00",
        media_type: "manga",
        status: "finished",
        num_volumes: 9,
        num_chapters: 29,
        authors: [
          {
            node: { id: 2463, first_name: "Ouji", last_name: "Hiroi" },
            role: "Story",
          },
          {
            node: { id: 2466, first_name: "Ikkyu", last_name: "Masa" },
            role: "Art",
          },
          {
            node: { id: 2467, first_name: "Kousuke", last_name: "Fujishima" },
            role: "Story",
          },
          {
            node: { id: 18777, first_name: "Ikku", last_name: "Masa" },
            role: "Art",
          },
        ],
      },
    },
    {
      node: {
        id: 4647,
        title: "Sakura no Ichiban!",
        main_picture: {
          medium: "https://api-cdn.myanimelist.net/images/manga/4/32274.jpg",
          large: "https://api-cdn.myanimelist.net/images/manga/4/32274l.jpg",
        },
        alternative_titles: {
          synonyms: [
            "Sakura's Best",
            "Taisho Komachi Jikenchou Sakura no Ichiban!",
          ],
          en: "Sakura's Best",
          ja: "大正小町事件帖櫻の一番!",
        },
        start_date: "2001",
        end_date: "2003",
        synopsis:
          "A young girl named Hinomori Asami starts her studies at the Sakura Hill School for Girls in Tokyo, but the capital is a dangerous place, and mysteries abound.\n\nSource:  Baka-Updates Manga",
        mean: 7.01,
        rank: 7606,
        popularity: 9006,
        num_list_users: 1090,
        num_scoring_users: 429,
        nsfw: "white",
        genres: [
          { id: 1, name: "Action" },
          { id: 17, name: "Martial Arts" },
          { id: 7, name: "Mystery" },
          { id: 22, name: "Romance" },
          { id: 23, name: "School" },
          { id: 36, name: "Slice of Life" },
        ],
        created_at: "1970-01-01T00:00:00+00:00",
        updated_at: "2018-07-16T10:24:15+00:00",
        media_type: "manga",
        status: "finished",
        num_volumes: 5,
        num_chapters: 25,
        authors: [
          {
            node: { id: 2363, first_name: "Yuna", last_name: "Kagesaki" },
            role: "Story & Art",
          },
        ],
      },
    },
    {
      node: {
        id: 106,
        title: "Cardcaptor Sakura",
        main_picture: {
          medium: "https://api-cdn.myanimelist.net/images/manga/1/173442.jpg",
          large: "https://api-cdn.myanimelist.net/images/manga/1/173442l.jpg",
        },
        alternative_titles: {
          synonyms: ["Cardcaptor Sakura: Master of the Clow", "CCS"],
          en: "Cardcaptor Sakura",
          ja: "カードキャプターさくら",
        },
        start_date: "1996-05-02",
        end_date: "2000-07-03",
        synopsis:
          '"Herein lie the Clow Cards—if their seal is broken, disaster shall befall this world..."\n\nSakura Kinomoto is an energetic and sweet 10-year-old girl attending Tomoeda Elementary School. One day not long after entering the fourth grade, Sakura finds a mysterious book titled "The Clow" hidden within her father\'s bookshelves. Upon opening it, a small, winged creature with an Osakan accent comes out of the book and introduces itself as Keroberos, the Creature of the Seal who guards magical cards known as the Clow Cards and keeps them from escaping the book.\n\nUnfortunately for the plushy guardian, it seems that the Clow Cards have already escaped—and now Sakura is tasked with capturing them before the cards unleash their powers and cause havoc all over Tomoeda! With the support of the tiny guardian who she nicknames "Kero" and her best friend Tomoyo Daidouji, Sakura must wield a magical bird-shaped key and use her new powers as the Cardcaptor to maintain peace and ensure that everything is alright.\n\n[Written by MAL Rewrite]',
        mean: 8.4,
        rank: 168,
        popularity: 162,
        num_list_users: 47106,
        num_scoring_users: 25282,
        nsfw: "white",
        genres: [
          { id: 2, name: "Adventure" },
          { id: 4, name: "Comedy" },
          { id: 10, name: "Fantasy" },
          { id: 16, name: "Magic" },
          { id: 22, name: "Romance" },
          { id: 25, name: "Shoujo" },
        ],
        created_at: "1970-01-01T00:00:00+00:00",
        updated_at: "2020-07-15T22:13:28+00:00",
        media_type: "manga",
        status: "finished",
        num_volumes: 12,
        num_chapters: 50,
        authors: [
          {
            node: { id: 1877, first_name: "", last_name: "CLAMP" },
            role: "Story & Art",
          },
        ],
      },
    },
    {
      node: {
        id: 11107,
        title: "Sakura-hime Kaden",
        main_picture: {
          medium: "https://api-cdn.myanimelist.net/images/manga/1/150583.jpg",
          large: "https://api-cdn.myanimelist.net/images/manga/1/150583l.jpg",
        },
        alternative_titles: {
          synonyms: [
            "Sakurahime Kaden",
            "Shiro Bara Gakuen Vampire Rose",
            "White Rose Academy Vampire Rose",
            "Tenshi no Kinka Maple Rose",
            "The Angelic Coin of Maple Rose",
            "I.O.N",
          ],
          en: "Sakura Hime: The Legend of Princess Sakura",
          ja: "桜姫華伝",
        },
        start_date: "2008-12-01",
        end_date: "2012-12-01",
        synopsis:
          "Sakura is a princess who lives alone with a few maids in a mansion deep in the mountains. She's been engaged to the prince of the country since she was born. She doesn't like that fact, as she wants to decide her fate on her own. However, one day, a messenger from the prince suddenly came to take her to the capital…\n\n(Source: Aerandria)\n\nIncluded one-shots:\nVolume 5: Shiro Bara Gakuen Vampire Rose (White Rose Academy Vampire Rose)\nVolume 6: Tenshi no Kinka Maple Rose (The Angelic Coin of Maple Rose)\nVolume 8: I.O.N",
        mean: 7.45,
        rank: 2913,
        popularity: 1040,
        num_list_users: 10505,
        num_scoring_users: 4091,
        nsfw: "white",
        genres: [
          { id: 1, name: "Action" },
          { id: 10, name: "Fantasy" },
          { id: 16, name: "Magic" },
          { id: 22, name: "Romance" },
          { id: 6, name: "Demons" },
          { id: 13, name: "Historical" },
          { id: 8, name: "Drama" },
          { id: 25, name: "Shoujo" },
        ],
        created_at: "1970-01-01T00:00:00+00:00",
        updated_at: "2020-07-03T10:25:14+00:00",
        media_type: "manga",
        status: "finished",
        num_volumes: 12,
        num_chapters: 55,
        authors: [
          {
            node: { id: 1878, first_name: "Arina", last_name: "Tanemura" },
            role: "Story & Art",
          },
        ],
      },
    },
  ],
  paging: {
    next:
      "https://api.myanimelist.net/v2/manga?offset=10&q=Sakurasou&fields=alternative_titles%2Cstart_date%2Cend_date%2Csynopsis%2Cmean%2Crank%2Cpopularity%2Cnum_list_users%2Cnum_scoring_users%2Cnsfw%2Cgenres%2Ccreated_at%2Cupdated_at%2Cmedia_type%2Cstatus%2Cmy_list_status%7Bstart_date%2Ctrue%2Cfinish_date%2Ctrue%2Cpriority%2Ctrue%2Cnum_times_reread%2Ctrue%2Creread_value%2Ctrue%2Ctags%2Ctrue%2Ccomments%2Ctrue%7D%2Cnum_volumes%2Cnum_chapters%2Cauthors%7Bauthors%7Bfirst_name%2Clast_name%7D%7D",
  },
};
